packages:
  - demos/*
  - libs/*
  - packages/*
  - tools/*

ignoredBuiltDependencies:
  - oxc-resolver

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild
  - nx
  - unrs-resolver

overrides:
  diff@>=4.0.0 <4.0.4: ">=4.0.4"
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
  js-yaml@<3.14.2: ">=3.14.2 <4.0.0"
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
  koa@>=3.0.1 <3.0.3: ">=3.0.3"
  qs@<6.14.1: ">=6.14.1"
  qs@>=6.7.0 <=6.14.1: ">=6.14.2"
  tar@<7.5.7: ">=7.5.7"
  tar@<=7.5.2: ">=7.5.3"
  tar@<=7.5.3: ">=7.5.4"
  undici@>=7.0.0 <7.18.2: ">=7.18.2"
  webpack@>=5.49.0 <5.104.0: ">=5.104.0"
  webpack@>=5.49.0 <=5.104.0: ">=5.104.1"
