packages:
  - demos/*
  - libs/*
  - packages/*
  - tools/*

ignoredBuiltDependencies:
  - oxc-resolver

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild
  - nx
  - unrs-resolver

overrides:
  koa@>=3.0.1 <3.0.3: ">=3.0.3"
