packages:
  - demos/*
  - libs/*
  - packages/*
  - tools/*

ignoredBuiltDependencies:
  - oxc-resolver

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild
  - nx
  - unrs-resolver

overrides:
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
  js-yaml@<3.14.2: ">=3.14.2 <4.0.0"
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
  koa@>=3.0.1 <3.0.3: ">=3.0.3"
