/**
 * Generate serialized Lexical editor states for `usj2Sa` in all 3 marker modes, and pin their
 * freshness against the committed fixtures.
 *
 * Run with: pnpm generate:test-data
 *
 * This test generates the static fixture files (`libs/test-data/src/data/2sa.lexical.*.ts`) used
 * by the data-driven selection tests (see `selection.utils*.data-driven.test.ts` in
 * `libs/shared-react/src/plugins/usj/annotation/`). Re-run it whenever `usj2Sa` or the platform
 * USJ editor adaptor changes.
 *
 * Generation itself is guarded by the GENERATE_TEST_DATA env var so it doesn't run during normal
 * `nx test platform` invocations. Without that var, this file instead runs as an always-on
 * FRESHNESS PIN: it rebuilds each mode's state in memory from the current `usj2Sa` + adaptor and
 * deep-compares it against the committed fixture. A mismatch means the fixtures are stale
 * relative to the live adaptor — regenerate and commit them with:
 *   GENERATE_TEST_DATA=1 pnpm generate:test-data   (from packages/platform)
 */
import { serializeEditorState, initialize } from "./usj-editor.adaptor";
import { writeFileSync } from "fs";
import { resolve } from "path";
import type { ViewOptions } from "shared-react";
import type { SerializedEditorState } from "lexical";
import { usj2Sa, lexicalEditable2Sa, lexicalVisible2Sa, lexicalHidden2Sa } from "test-data";

const REGENERATE_COMMAND = "GENERATE_TEST_DATA=1 pnpm generate:test-data (from packages/platform)";

const outputDir = resolve(__dirname, "../../../../../libs/test-data/src/data");

const modes = [
  {
    markerMode: "editable" as const,
    exportName: "lexicalEditable2Sa",
    fileName: "2sa.lexical.editable.ts",
    committed: lexicalEditable2Sa,
  },
  {
    markerMode: "visible" as const,
    exportName: "lexicalVisible2Sa",
    fileName: "2sa.lexical.visible.ts",
    committed: lexicalVisible2Sa,
  },
  {
    markerMode: "hidden" as const,
    exportName: "lexicalHidden2Sa",
    fileName: "2sa.lexical.hidden.ts",
    committed: lexicalHidden2Sa,
  },
];

/**
 * Strips function references (e.g. onClick on note callers) that can't survive a JSON round
 * trip — the same transform the generator applies before writing a fixture file — so a freshly
 * built state and the JSON-backed committed fixture compare on structure alone.
 */
function toComparableJson(value: unknown): unknown {
  return JSON.parse(JSON.stringify(value, (_key, v) => (typeof v === "function" ? undefined : v)));
}

describe("2SA Lexical states", () => {
  for (const mode of modes) {
    const title = process.env.GENERATE_TEST_DATA
      ? `generates ${mode.markerMode} mode state`
      : `${mode.markerMode} mode fixture is fresh (matches the live usj2Sa + adaptor)`;

    it(title, () => {
      const viewOptions: ViewOptions = {
        markerMode: mode.markerMode,
        noteMode: "expanded",
        hasSpacing: false,
        isFormattedFont: false,
      };

      initialize(undefined, undefined);
      const serializedState: SerializedEditorState = serializeEditorState(usj2Sa, viewOptions);

      if (process.env.GENERATE_TEST_DATA) {
        // Remove any function references (e.g., onClick on note callers) that can't be serialized
        const json = JSON.stringify(
          serializedState,
          (_key, value) => (typeof value === "function" ? undefined : value),
          2,
        );

        const content = `// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck -- auto-generated serialized editor state; custom node properties are not in SerializedLexicalNode
import type { SerializedEditorState } from "lexical";

/**
 * Serialized Lexical editor state for \`usj2Sa\` (2 Samuel chapters 1-2) in "${mode.markerMode}" marker mode.
 *
 * Auto-generated by packages/platform/src/editor/adaptors/generate-2sa-lexical-states.test.ts.
 * Re-run the test when \`usj2Sa\` or the platform USJ editor adaptor changes:
 *   pnpm generate:test-data   (from packages/platform)
 */
export const ${mode.exportName}: SerializedEditorState = ${json};
`;

        const filePath = resolve(outputDir, mode.fileName);
        writeFileSync(filePath, content, "utf8");
        // Log so the test runner output shows what was generated
        // eslint-disable-next-line no-console -- test output
        console.log(`Wrote ${filePath} (${content.length} chars)`);
        expect(serializedState.root.children.length).toBeGreaterThan(0);
        return;
      }

      // Freshness pin: fails loudly (with the regeneration command) when the committed fixture
      // no longer matches what the current usj2Sa + adaptor would produce.
      expect(
        toComparableJson(serializedState),
        `libs/test-data/src/data/${mode.fileName} is stale. Regenerate with: ${REGENERATE_COMMAND}`,
      ).toEqual(toComparableJson(mode.committed));
    });
  }
});
