/**
 * Generate serialized Lexical editor states for `usj2Sa` in all 3 marker modes.
 *
 * Run with: pnpm generate:test-data
 *
 * This test generates static fixture files used by the data-driven selection tests.
 * It only needs to be run when `usj2Sa` or the platform USJ editor adaptor changes.
 *
 * Guarded by the GENERATE_TEST_DATA env var so it doesn't run during normal
 * `nx test platform` invocations.
 */
import { serializeEditorState, initialize } from "./usj-editor.adaptor";
import { writeFileSync } from "fs";
import { resolve } from "path";
import type { ViewOptions } from "shared-react";
import { usj2Sa } from "test-data";

describe.skipIf(!process.env.GENERATE_TEST_DATA)("generate 2SA Lexical states", () => {
  const outputDir = resolve(__dirname, "../../../../../libs/test-data/src/data");

  const modes = [
    {
      markerMode: "editable" as const,
      exportName: "lexicalEditable2Sa",
      fileName: "2sa.lexical.editable.ts",
    },
    {
      markerMode: "visible" as const,
      exportName: "lexicalVisible2Sa",
      fileName: "2sa.lexical.visible.ts",
    },
    {
      markerMode: "hidden" as const,
      exportName: "lexicalHidden2Sa",
      fileName: "2sa.lexical.hidden.ts",
    },
  ];

  for (const mode of modes) {
    it(`generates ${mode.markerMode} mode state`, () => {
      const viewOptions: ViewOptions = {
        markerMode: mode.markerMode,
        noteMode: "expanded",
        hasSpacing: false,
        isFormattedFont: false,
      };

      initialize(undefined, undefined);
      const serializedState = serializeEditorState(usj2Sa, viewOptions);

      // Remove any function references (e.g., onClick on note callers) that can't be serialized
      const json = JSON.stringify(
        serializedState,
        (_key, value) => (typeof value === "function" ? undefined : value),
        2,
      );

      const content = `// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck -- auto-generated serialized editor state; custom node properties are not in SerializedLexicalNode
import type { SerializedEditorState } from "lexical";

/**
 * Serialized Lexical editor state for \`usj2Sa\` (2 Samuel chapters 1-2) in "${mode.markerMode}" marker mode.
 *
 * Auto-generated by packages/platform/src/editor/adaptors/generate-2sa-lexical-states.test.ts.
 * Re-run the test when \`usj2Sa\` or the platform USJ editor adaptor changes:
 *   nx generate:test-data platform-editor
 */
export const ${mode.exportName}: SerializedEditorState = ${json};
`;

      const filePath = resolve(outputDir, mode.fileName);
      writeFileSync(filePath, content, "utf8");
      // Log so the test runner output shows what was generated
      // eslint-disable-next-line no-console -- test output
      console.log(`Wrote ${filePath} (${content.length} chars)`);
      expect(serializedState.root.children.length).toBeGreaterThan(0);
    });
  }
});
