import postcss from "postcss";
import { classify, mirrorRtl, type Declaration } from "./classifier.js";

export interface ConvertOptions {
  source?: string;
  generatedAt?: Date;
  baseScss?: string;
}

export interface ConvertWarnings {
  unknownProperties: string[];
  skippedTableMarkers: string[];
  skippedSelectors: string[];
  duplicateMarkers: string[];
  baseOverlapMarkers: string[];
}

export interface ConvertResult {
  scss: string;
  markerCount: number;
  warnings: ConvertWarnings;
}

export function convert(css: string, options: ConvertOptions = {}): ConvertResult {
  const root = postcss.parse(css);
  const markers = new Map<string, MarkerBuckets>();
  const markerOrder: string[] = [];
  const warnings: ConvertWarnings = {
    unknownProperties: [],
    skippedTableMarkers: [],
    skippedSelectors: [],
    duplicateMarkers: [],
    baseOverlapMarkers: [],
  };
  const unknownSeen = new Set<string>();
  const tableSeen = new Set<string>();
  const skippedSeen = new Set<string>();
  const duplicateSeen = new Set<string>();

  root.walkAtRules("font-face", (at) => {
    at.remove();
  });

  root.walkRules((rule) => {
    for (const selector of rule.selectors) {
      const match = selector.match(MARKER_SELECTOR_RE);
      if (!match) {
        const trimmed = selector.trim();
        if (!skippedSeen.has(trimmed)) {
          skippedSeen.add(trimmed);
          warnings.skippedSelectors.push(trimmed);
        }
        continue;
      }

      const marker = match[1];
      if (TABLE_MARKER_RE.test(marker)) {
        if (!tableSeen.has(marker)) {
          tableSeen.add(marker);
          warnings.skippedTableMarkers.push(marker);
        }
        continue;
      }

      const existing = markers.get(marker);
      const buckets: MarkerBuckets = existing ?? {
        typography: [],
        nonDirectional: [],
        directional: [],
      };
      if (!existing) {
        markers.set(marker, buckets);
        markerOrder.push(marker);
      } else if (!duplicateSeen.has(marker)) {
        duplicateSeen.add(marker);
        warnings.duplicateMarkers.push(marker);
      }

      rule.walkDecls((decl) => {
        const declaration: Declaration = { property: decl.prop, value: decl.value };
        const result = classify(declaration);
        if (result.unknown) {
          const key = decl.prop.toLowerCase();
          if (!unknownSeen.has(key)) {
            unknownSeen.add(key);
            warnings.unknownProperties.push(key);
          }
        }
        bucketFor(buckets, result.bucket).push(declaration);
      });
    }
  });

  if (options.baseScss) {
    const baseMarkers = extractBaseMarkers(options.baseScss);
    for (const marker of markerOrder) {
      if (baseMarkers.has(marker)) warnings.baseOverlapMarkers.push(marker);
    }
  }

  const scss = render({
    markerOrder,
    markers,
    warnings,
    source: options.source,
    generatedAt: options.generatedAt ?? new Date(),
    baseProvided: Boolean(options.baseScss),
  });

  return { scss, markerCount: markerOrder.length, warnings };
}

interface MarkerBuckets {
  typography: Declaration[];
  nonDirectional: Declaration[];
  directional: Declaration[];
}

interface RenderInput {
  markerOrder: string[];
  markers: Map<string, MarkerBuckets>;
  warnings: ConvertWarnings;
  source?: string;
  generatedAt: Date;
  baseProvided: boolean;
}

function bucketFor(buckets: MarkerBuckets, bucket: ReturnType<typeof classify>["bucket"]) {
  switch (bucket) {
    case "typography":
      return buckets.typography;
    case "non-directional":
      return buckets.nonDirectional;
    case "directional":
      return buckets.directional;
  }
}

function extractBaseMarkers(baseScss: string): Set<string> {
  const markers = new Set<string>();
  let match: RegExpExecArray | null;
  const re = new RegExp(BASE_MARKER_RE.source, "g");
  while ((match = re.exec(baseScss)) !== null) markers.add(match[1]);
  return markers;
}

function render({
  markerOrder,
  markers,
  warnings,
  source,
  generatedAt,
  baseProvided,
}: RenderInput): string {
  const lines: string[] = [];
  lines.push("/* Generated by tools/pt9-css-converter — do not edit by hand.");
  if (source) lines.push(` * Source: ${source}`);
  lines.push(` * Generated at: ${generatedAt.toISOString()}`);
  lines.push(` * Markers: ${markerOrder.length}`);
  if (hasAnyWarning(warnings, baseProvided)) {
    lines.push(" *");
    lines.push(" * Warnings:");
    if (warnings.unknownProperties.length)
      lines.push(
        ` *   Unknown properties (defaulted to typography): ${warnings.unknownProperties.join(", ")}`,
      );
    if (warnings.skippedTableMarkers.length)
      lines.push(` *   Skipped table markers: ${warnings.skippedTableMarkers.join(", ")}`);
    if (warnings.skippedSelectors.length)
      lines.push(` *   Skipped non-marker selectors: ${warnings.skippedSelectors.join(", ")}`);
    if (warnings.duplicateMarkers.length)
      lines.push(
        ` *   Markers seen more than once (declarations merged): ${warnings.duplicateMarkers.join(", ")}`,
      );
    if (warnings.baseOverlapMarkers.length)
      lines.push(
        ` *   Markers also styled in base _usj-nodes.scss (cascade-resolved): ${warnings.baseOverlapMarkers.join(", ")}`,
      );
  }
  lines.push(" */");
  lines.push("");

  for (const marker of markerOrder) {
    const buckets = markers.get(marker);
    if (!buckets) continue;
    emitBlock(lines, `.formatted-font .usfm_${marker}`, buckets.typography);
    emitBlock(lines, `.text-spacing .usfm_${marker}`, buckets.nonDirectional);
    if (buckets.directional.length) {
      emitBlock(lines, `.text-spacing[dir='ltr'] .usfm_${marker}`, buckets.directional);
      emitBlock(
        lines,
        `.text-spacing[dir='rtl'] .usfm_${marker}`,
        buckets.directional.map(mirrorRtl),
      );
    }
  }

  return lines.join("\n") + "\n";
}

function emitBlock(lines: string[], selector: string, declarations: Declaration[]): void {
  if (!declarations.length) return;
  lines.push(`${selector} {`);
  for (const decl of declarations) lines.push(`  ${decl.property}: ${decl.value};`);
  lines.push("}");
}

function hasAnyWarning(w: ConvertWarnings, baseProvided: boolean): boolean {
  return (
    w.unknownProperties.length > 0 ||
    w.skippedTableMarkers.length > 0 ||
    w.skippedSelectors.length > 0 ||
    w.duplicateMarkers.length > 0 ||
    (baseProvided && w.baseOverlapMarkers.length > 0)
  );
}

const TABLE_MARKER_RE = /^(tr|tc\d+|th\d+|tcr\d+|tcc\d+|thr\d+|thc\d+)$/;
const MARKER_SELECTOR_RE = /^\s*\.usfm_([a-zA-Z][a-zA-Z0-9_-]*)\s*$/;
const BASE_MARKER_RE = /\.usfm_([a-zA-Z][a-zA-Z0-9_-]*)/;
